//#include <stdio.h>

//#include "typedefs.h"
//#include "iface_globals.h"
//#include "snd.h"
namespace DigitalEeel
{
    public static partial class SAIS
    {
        public static void load_all_sfx()
        {
            // combat
            Load_WAV("sounds/combat/beam1.wav", sfxsamples.WAV_BEAM1);
            Load_WAV("sounds/combat/beam2.wav", sfxsamples.WAV_BEAM2);
            Load_WAV("sounds/combat/beam3.wav", sfxsamples.WAV_BEAM3);
            Load_WAV("sounds/combat/beam4.wav", sfxsamples.WAV_BEAM4);
            Load_WAV("sounds/combat/beam5.wav", sfxsamples.WAV_BEAM5);
            Load_WAV("sounds/combat/beam6.wav", sfxsamples.WAV_BEAM6);
            Load_WAV("sounds/combat/beam7.wav", sfxsamples.WAV_BEAM7);
            Load_WAV("sounds/combat/misl1.wav", sfxsamples.WAV_PROJ1);
            Load_WAV("sounds/combat/misl1.wav", sfxsamples.WAV_PROJ2);
            Load_WAV("sounds/combat/misl3.wav", sfxsamples.WAV_PROJ3);
            Load_WAV("sounds/combat/misl1.wav", sfxsamples.WAV_PROJ4);
            Load_WAV("sounds/combat/misl1.wav", sfxsamples.WAV_PROJ5);
            Load_WAV("sounds/combat/pgun1.wav", sfxsamples.WAV_PROJ6);
            Load_WAV("sounds/combat/pgun2.wav", sfxsamples.WAV_PROJ7);
            Load_WAV("sounds/combat/pgun3.wav", sfxsamples.WAV_PROJ8);
            Load_WAV("sounds/combat/pgun4.wav", sfxsamples.WAV_PROJ9);
            Load_WAV("sounds/combat/pgun5.wav", sfxsamples.WAV_PROJ10);
            Load_WAV("sounds/combat/pgun6.wav", sfxsamples.WAV_PROJ11);
            Load_WAV("sounds/combat/lowboom.wav", sfxsamples.WAV_HIT1);
            Load_WAV("sounds/combat/bulhit02.wav", sfxsamples.WAV_HIT2);
            Load_WAV("sounds/combat/plashit01.wav", sfxsamples.WAV_HIT3);
            Load_WAV("sounds/combat/lowboom.wav", sfxsamples.WAV_HIT4);
            Load_WAV("sounds/combat/lowboom.wav", sfxsamples.WAV_HIT5);
            Load_WAV("sounds/combat/explo01.wav", sfxsamples.WAV_EXPLO1);
            Load_WAV("sounds/combat/explo02.wav", sfxsamples.WAV_EXPLO2);
            Load_WAV("sounds/combat/shield02.wav", sfxsamples.WAV_SHIELD);
            Load_WAV("sounds/combat/cloak_in.wav", sfxsamples.WAV_CLOAKIN);
            Load_WAV("sounds/combat/cloak_out.wav", sfxsamples.WAV_CLOAKOUT);
            Load_WAV("sounds/combat/boardship.wav", sfxsamples.WAV_BOARD);
            Load_WAV("sounds/combat/sys_dmg.wav", sfxsamples.WAV_SYSDAMAGE);
            Load_WAV("sounds/combat/sys_hit.wav", sfxsamples.WAV_SYSHIT1);
            Load_WAV("sounds/combat/sys_hit_2.wav", sfxsamples.WAV_SYSHIT2);
            Load_WAV("sounds/combat/sys_fixed.wav", sfxsamples.WAV_SYSFIXED);
            Load_WAV("sounds/combat/teleport.wav", sfxsamples.WAV_TELEPORT);
            Load_WAV("sounds/combat/fieryfury.wav", sfxsamples.WAV_FIERYFURY);
            Load_WAV("sounds/combat/fighter.wav", sfxsamples.WAV_FIGHTERLAUNCH);
            Load_WAV("sounds/combat/sim_end.wav", sfxsamples.WAV_ENDSIMULATION);
            // interface
            Load_WAV("sounds/beep_yes.wav", sfxsamples.WAV_YES);
            Load_WAV("sounds/beep_no.wav", sfxsamples.WAV_NO);
            Load_WAV("sounds/beep_accept.wav", sfxsamples.WAV_ACCEPT);
            Load_WAV("sounds/beep_decline.wav", sfxsamples.WAV_DECLINE);
            Load_WAV("sounds/beep_dot.wav", sfxsamples.WAV_DOT);
            Load_WAV("sounds/beep_dot2.wav", sfxsamples.WAV_DOT2);
            Load_WAV("sounds/beep_select.wav", sfxsamples.WAV_SELECT);
            Load_WAV("sounds/beep_deselect.wav", sfxsamples.WAV_DESELECT);
            Load_WAV("sounds/beep_selectstar.wav", sfxsamples.WAV_SELECTSTAR);
            Load_WAV("sounds/beep_info.wav", sfxsamples.WAV_INFO);
            Load_WAV("sounds/beep_selship.wav", sfxsamples.WAV_SELECTSHIP);
            Load_WAV("sounds/beep_wait.wav", sfxsamples.WAV_WAIT);
            Load_WAV("sounds/swut.wav", sfxsamples.WAV_SLIDER);
            Load_WAV("sounds/install.wav", sfxsamples.WAV_INSTALL);
            Load_WAV("sounds/install2.wav", sfxsamples.WAV_INSTALL2);
            Load_WAV("sounds/lock.wav", sfxsamples.WAV_LOCK);
            Load_WAV("sounds/depart02.wav", sfxsamples.WAV_DEPART);
            Load_WAV("sounds/arrive02.wav", sfxsamples.WAV_ARRIVE);
            Load_WAV("sounds/hyperdrv.wav", sfxsamples.WAV_HYPERDRIVE);
            Load_WAV("sounds/foldmove.wav", sfxsamples.WAV_FOLDSPACE);
            Load_WAV("sounds/radar1.wav", sfxsamples.WAV_RADAR);
            Load_WAV("sounds/scan_loop.wav", sfxsamples.WAV_SCANNER);
            Load_WAV("sounds/bridge_loop.wav", sfxsamples.WAV_BRIDGE);
            Load_WAV("sounds/message.wav", sfxsamples.WAV_MESSAGE);
            Load_WAV("sounds/message2.wav", sfxsamples.WAV_TANRUMESSAGE);
            Load_WAV("sounds/pay_loop.wav", sfxsamples.WAV_PAYMERC);
            Load_WAV("sounds/trade01.wav", sfxsamples.WAV_TRADE);
            Load_WAV("sounds/cash02.wav", sfxsamples.WAV_CASH);
            Load_WAV("sounds/probe_l.wav", sfxsamples.WAV_PROBE_LAUNCH);
            Load_WAV("sounds/probe_d.wav", sfxsamples.WAV_PROBE_DEST);
            Load_WAV("sounds/fomax_hi.wav", sfxsamples.WAV_FOMAX_HI);
            Load_WAV("sounds/fomax_bye.wav", sfxsamples.WAV_FOMAX_BYE);
            Load_WAV("sounds/fomax_wish.wav", sfxsamples.WAV_FOMAX_WISH);
            Load_WAV("sounds/timer.wav", sfxsamples.WAV_TIMER);
            Load_WAV("sounds/warning.wav", sfxsamples.WAV_WARNING);
            Load_WAV("sounds/opticals.wav", sfxsamples.WAV_OPTICALS);
            Load_WAV("sounds/alien1.wav", sfxsamples.WAV_TITLE1);
            Load_WAV("sounds/alien2.wav", sfxsamples.WAV_TITLE2);
            Load_WAV("sounds/alien3.wav", sfxsamples.WAV_TITLE3);
            Load_WAV("sounds/titzap01.wav", sfxsamples.WAV_TITLE4);
            Load_WAV("sounds/titzap02.wav", sfxsamples.WAV_TITLE5);
            Load_WAV("sounds/logo.wav", sfxsamples.WAV_LOGO);
            // race encounters
            Load_WAV("sounds/races/klakar.wav", sfxsamples.WAV_KLAKAR);
            Load_WAV("sounds/races/zorg.wav", sfxsamples.WAV_ZORG);
            Load_WAV("sounds/races/muktian.wav", sfxsamples.WAV_MUKTIAN);
            Load_WAV("sounds/races/garthan.wav", sfxsamples.WAV_GARTHAN);
            Load_WAV("sounds/races/tanru.wav", sfxsamples.WAV_TANRU);
            Load_WAV("sounds/races/urluquai.wav", sfxsamples.WAV_URLUQUAI);
            Load_WAV("sounds/races/kawangi.wav", sfxsamples.WAV_KAWANGI);
            // events
            Load_WAV("sounds/blakhole.wav", sfxsamples.WAV_BLACKHOLE);
            Load_WAV("sounds/blakhol2.wav", sfxsamples.WAV_BLACKHOLEDEATH);
            Load_WAV("sounds/collapse.wav", sfxsamples.WAV_COLLAPSER);
            // cards
            Load_WAV("sounds/cards/ally.wav", sfxsamples.WAV_ALLY);
            Load_WAV("sounds/cards/flare_loop.wav", sfxsamples.WAV_FLARE);
            Load_WAV("sounds/cards/intruder_loop.wav", sfxsamples.WAV_SPY);
            Load_WAV("sounds/cards/nova_loop.wav", sfxsamples.WAV_NOVA);
            Load_WAV("sounds/cards/intruder_loop.wav", sfxsamples.WAV_SABOTEUR);
            Load_WAV("sounds/cards/whales.wav", sfxsamples.WAV_WHALES);
            Load_WAV("sounds/cards/cube_loop.wav", sfxsamples.WAV_CUBE);
            Load_WAV("sounds/cards/hulk_loop.wav", sfxsamples.WAV_SPACEHULK);
            Load_WAV("sounds/cards/gas_loop.wav", sfxsamples.WAV_GASGIANT);
            Load_WAV("sounds/cards/no_planet.wav", sfxsamples.WAV_NOPLANET);
            // items
            Load_WAV("sounds/cards/weapon.wav", sfxsamples.WAV_WEAPON);
            Load_WAV("sounds/cards/system_loop.wav", sfxsamples.WAV_SYSTEM);
            Load_WAV("sounds/cards/device.wav", sfxsamples.WAV_DEVICE);
            Load_WAV("sounds/cards/lifeform.wav", sfxsamples.WAV_LIFEFORM);
            Load_WAV("sounds/cards/drive_loop.wav", sfxsamples.WAV_DRIVE);
            // artifacts
            Load_WAV("sounds/cards/platinum.wav", sfxsamples.WAV_PLATINUM);
            Load_WAV("sounds/cards/titanium.wav", sfxsamples.WAV_TITANIUM);
            Load_WAV("sounds/cards/brass.wav", sfxsamples.WAV_BRASS);
            Load_WAV("sounds/cards/plastic.wav", sfxsamples.WAV_PLASTIC);
            Load_WAV("sounds/cards/cenotaph.wav", sfxsamples.WAV_CENOTAPH);
            Load_WAV("sounds/cards/torc.wav", sfxsamples.WAV_TORC);
            Load_WAV("sounds/cards/gong.wav", sfxsamples.WAV_GONG);
            Load_WAV("sounds/cards/mantle.wav", sfxsamples.WAV_MANTLE);
            Load_WAV("sounds/cards/whistle.wav", sfxsamples.WAV_WHISTLE);
            Load_WAV("sounds/cards/horloge_loop.wav", sfxsamples.WAV_HORLOGE);
            Load_WAV("sounds/cards/toy.wav", sfxsamples.WAV_TOY);
            Load_WAV("sounds/cards/codex.wav", sfxsamples.WAV_CODEX);
            Load_WAV("sounds/cards/sculpture.wav", sfxsamples.WAV_SCULPTURE);
            Load_WAV("sounds/cards/conograph_loop.wav", sfxsamples.WAV_CONOGRAPH);
            Load_WAV("sounds/cards/conograph_use.wav", sfxsamples.WAV_CONOGRAPH2);
            Load_WAV("sounds/cards/monocle.wav", sfxsamples.WAV_MONOCLE);
            Load_WAV("sounds/cards/bauble.wav", sfxsamples.WAV_BAUBLE);
            Load_WAV("sounds/cards/mirror.wav", sfxsamples.WAV_MIRROR);
            Load_WAV("sounds/cards/mummy.wav", sfxsamples.WAV_MUMMY);
            Load_WAV("sounds/cards/monolith.wav", sfxsamples.WAV_MONOLITH);
            // music
            Load_WAV("sounds/music/start.wav", sfxsamples.WAV_MUS_START);
            Load_WAV("sounds/music/splash.wav", sfxsamples.WAV_MUS_SPLASH);
            Load_WAV("sounds/music/theme.wav", sfxsamples.WAV_MUS_THEME);
            Load_WAV("sounds/music/title.wav", sfxsamples.WAV_MUS_TITLE);
            Load_WAV("sounds/music/death.wav", sfxsamples.WAV_MUS_DEATH);
            Load_WAV("sounds/music/victory.wav", sfxsamples.WAV_MUS_VICTORY);
            Load_WAV("sounds/music/combat.wav", sfxsamples.WAV_MUS_COMBAT);
            Load_WAV("sounds/music/nebula.wav", sfxsamples.WAV_MUS_NEBULA);
            Load_WAV("sounds/music/hiscore.wav", sfxsamples.WAV_MUS_HISCORE);
            Load_WAV("sounds/music/rock.wav", sfxsamples.WAV_MUS_ROCK);
            Load_WAV("sounds/music/simulator.wav", sfxsamples.WAV_MUS_SIMULATOR);
        }
    }
}